$primary = rgb(ffb2ba)
$surface = rgb(181212)
$secondary = rgb(e5bdc0)
$error = rgb(ffb4ab)
$tertiary = rgb(e9bf8e)
$surface_lowest = rgb(120d0d)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
