color0 #111416
color1 #ffb4ab
color2 #7dd0ff
color3 #b6c9d7
color4 #cbc1e9
color5 #7dd0ff
color6 #b6c9d7
color7 #e1e2e5
color8 #8b9297
color9 #ffb4ab
color10 #7dd0ff
color11 #b6c9d7
color12 #cbc1e9
color13 #7dd0ff
color14 #b6c9d7
color15 #e1e2e5

cursor                #e1e2e5
cursor_text_color     #111416
background            #111416
foreground            #e1e2e5
selection_foreground  #c0c7cd
selection_background  #41484d
active_border_color   #7dd0ff
inactive_border_color #41484d
url_color             #7dd0ff

active_tab_foreground   #00344a
active_tab_background   #7dd0ff
inactive_tab_foreground #c0c7cd
inactive_tab_background #41484d
cursor_trail_color      #c0c7cd
