color0 #181212
color1 #ffb4ab
color2 #ffb2ba
color3 #e5bdc0
color4 #e9bf8e
color5 #ffb2ba
color6 #e5bdc0
color7 #ece0e0
color8 #9f8c8d
color9 #ffb4ab
color10 #ffb2ba
color11 #e5bdc0
color12 #e9bf8e
color13 #ffb2ba
color14 #e5bdc0
color15 #ece0e0

cursor                #ece0e0
cursor_text_color     #181212
background            #181212
foreground            #ece0e0
selection_foreground  #d7c1c3
selection_background  #524344
active_border_color   #ffb2ba
inactive_border_color #524344
url_color             #ffb2ba

active_tab_foreground   #5f1223
active_tab_background   #ffb2ba
inactive_tab_foreground #d7c1c3
inactive_tab_background #524344
cursor_trail_color      #d7c1c3
