source = hyprland/var.conf
source = hyprland/env.conf
source = hyprland/general.conf
source = hyprland/keybinds.conf
source = hyprland/exec.conf
source = hyprland/rules.conf

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24




windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
source = ign_monitors.conf
source = /home/xiro/.config/hypr/noctalia/noctalia-colors.conf
