gesture = 3, swipe, move,
gesture = 3, pinch, float
gesture = 4, up, fullscreen, 2
gesture = 4, horizontal, workspace

bind = $mod, T, exec, $terminal
bind = $mod, Q, killactive,
bind = $mod, V, togglefloating,
bindr = $mod, SUPER_L, exec, $menu
bind = $mod, P, pseudo, # dwindle
bind = $mod, J, layoutmsg, togglesplit # dwindle

bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

bind = $mod alt, 1, movetoworkspace, 1
bind = $mod alt, 2, movetoworkspace, 2
bind = $mod alt, 3, movetoworkspace, 3
bind = $mod alt, 4, movetoworkspace, 4
bind = $mod alt, 5, movetoworkspace, 5
bind = $mod alt, 6, movetoworkspace, 6
bind = $mod alt, 7, movetoworkspace, 7
bind = $mod alt, 8, movetoworkspace, 8
bind = $mod alt, 9, movetoworkspace, 9
bind = $mod alt, 0, movetoworkspace, 10

bind = $mod, mouse_down, workspace, e+1
bind = $mod, mouse_up, workspace, e-1

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

# bindd = Super, L,
bindld = Super+Shift, L, Suspend system, exec, systemctl suspend || loginctl suspend # Sleep
bindl=,switch:on:Lid Switch, exec, systemctl suspend || loginctl suspend # [hidden] Suspend when laptop lid is closed, uncomment if for whatever reason it's not the default behavior
